sudo: required

branches:
  only:
  - master

services:
- docker

env:
  global:
  - BUILD=${TRAVIS_COMMIT::8}
  - DOCKER_COMPOSE_VERSION=1.22.0

language: generic

cache:
  directories:
  - "$HOME/composer/"

before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

before_script:
- make up
- make install

script:
- make cs-check
- make phpstan
- make test
