version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3.7.4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: 1234

  php:
    build: docker/php
    environment:
      - AMQP_HOST=rabbitmq
      - AMQP_USER=test
      - AMQP_PASS=1234
    volumes:
      - ./:/app
