version: '3.7'

services:
  test:
    build: docker/php
    environment:
    - AMQP_HOST=rabbitmq
    - AMQP_USER=test
    - AMQP_PASS=1234
    volumes:
    - ./:/app:cached

  phpstan:
    build: docker/phpqa
    volumes:
    - ./:/app:cached
    working_dir: /app
    command: ["phpstan", "analyse", "-l1", "--no-interaction", "--no-progress", "src", "tests"]
